services:
  python: 
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app

  php:
    image: php:7.4-apache
    ports:
      - '8080:80'
    volumes:
      - ./php:/var/www/html
      
